version: "3"
services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  scheduler:
    build: ./airflow
    command: scheduler
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ${CODE_DIRECTORY}/datasdoc/airflow/dags:/opt/airflow/dags
      - ${CODE_DIRECTORY}/datasdoc/airflow/logs:/opt/airflow/logs
      - ${CODE_DIRECTORY}/datasdoc/airflow/plugins:/opt/airflow/plugins
      - ${CODE_DIRECTORY}/datasdoc/airflow/scripts:/opt/airflow/scripts
      - ~/.google/credentials/:/.google/credentials

  webserver:
    build: ./airflow
    entrypoint: ./scripts/entrypoint.sh
    restart: on-failure
    depends_on:
      - postgres
      - scheduler
    env_file:
      - .env
    volumes:
      - ${CODE_DIRECTORY}/datasdoc/airflow/dags:/opt/airflow/dags
      - ${CODE_DIRECTORY}/datasdoc/airflow/logs:/opt/airflow/logs
      - ${CODE_DIRECTORY}/datasdoc/airflow/plugins:/opt/airflow/plugins
      - ~/.google/credentials/:/.google/credentials:ro
      - ./scripts:/opt/airflow/scripts

    user: "${AIRFLOW_UID:-50000}:0"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /home/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  postgres-db-volume:
